config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'more-info', to: 'home#more_info'

  #TODO: Errors Pages
  #get '/404', to: 'errors#not_found'

  resources :leads
  get 'interested', to: 'leads#interested'
  get 'thank-you', to: 'leads#thank_you'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
  validates :first_name, :last_name, :gender, :age, :email, :phone_number, presence: true

  enum gender: { male: 0, female: 1, other: 2 }

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index; end

  def more_info; end

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :authenticate_user!, except: %i[interested thank_you create]
  before_action :set_lead, except: %i[interested thank_you index new create]

  def interested
    @lead = Lead.new
  end

  def thank_you
  end

  def index
    @leads = Lead.all
  end

  def show
  end

  def new
    @lead = Lead.new
  end

  def create
    @lead = Lead.new(lead_params)
    if @lead.save
      redirect_to thank_you_path, success: 'Congrats! SFC Pinon will be in touch soon.'
    else
      render :interested, error: @lead.errors.full_messages.to_sentence
    end
  end

  def edit
  end

  def update
    if @lead.update(lead_params)
      redirect_to @lead, success: 'Successfully updated.'
    else
      render :edit, error: @lead.errors.full_messages.to_sentence
    end
  end

  def destroy
    name = @lead.full_name
    @lead.destroy
    redirect_to leads_path, success: "Successfully removed #{name}."
  end

  private
    def set_lead
      @lead = Lead.find(params[:id])
    end

    def lead_params
      params.require(:lead).permit(
        :first_name,
        :last_name,
        :email,
        :phone_number,
        :street,
        :city,
        :state,
        :zip,
        :active_contact,
        :is_army,
        :comment,
        :note
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_phone(number)
    number = number.delete("^0-9")
    # for numbers like '1-800-123-1234'
    if number.length == 11 && number[0] == '1'
      return number_to_phone(number[1..-1], pattern: /(\d{3})(\d{3})(\d{4})$/, area_code: true, delimiter: '-')
    end

    # for numbers like '800-123-1234'
    return number_to_phone(number, pattern: /(\d{3})(\d{3})(\d{4})$/, area_code: true, delimiter: '-') if number.length == 10

    # for foreign numbers
    number_to_phone(number, pattern: /(\d{1,4})(\d{4})(\d{4})$/, delimiter: '-')
  end

  def flash_message_class(type)
    case type
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'warning' then "alert alert-warning"
      when 'error', 'danger' then "alert alert-danger"
    end
  end
end

app/views/home/index.html.erb
<div class="px-4 pt-5 my-5 text-center border-bottom">

  <h1 class="display-4 fw-bold">Centered Screenshot</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Something about something with more info. Something about something with more info. Something about something with more info. Something about something with more info. Something about something with more info.</p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
      <%= link_to 'Recruit Me', interested_path, class: 'btn btn-primary btn-lg px-4 me-sm-3' %>
      <%= link_to 'More Info', more_info_path, class: 'btn btn-outline-secondary btn-lg px-4' %>
    </div>
  </div>

  <div class="overflow-hidden" style="max-height: 30vh;">
    <div class="container px-5">
      <img src="https://via.placeholder.com/700x300.png" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" loading="lazy">
    </div>
  </div>

</div>

app/views/home/more_info.html.erb
<!-- 3 COLUMN -->
<div class="container px-4 py-5" id="hanging-icons">
  <h2 class="pb-2">The Army is Great</h2>
  <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">

    <div class="col d-flex align-items-start">
      <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
        <img src='https://via.placeholder.com/40x40.png'>
      </div>
      <div>
        <h2>Featured title</h2>
        <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
        <a href="#" class="btn btn-primary">
          Primary button
        </a>
      </div>
    </div>

    <div class="col d-flex align-items-start">
      <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
        <img src='https://via.placeholder.com/40x40.png'>
      </div>
      <div>
        <h2>Featured title</h2>
        <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
        <a href="#" class="btn btn-primary">
          Primary button
        </a>
      </div>
    </div>

    <div class="col d-flex align-items-start">
      <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
        <img src='https://via.placeholder.com/40x40.png'>
        <%# <svg class="bi" width="1em" height="1em"><use xlink:href="#tools"></use></svg> %>
      </div>
      <div>
        <h2>Featured title</h2>
        <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
        <a href="#" class="btn btn-primary">
          Primary button
        </a>
      </div>
    </div>

  </div>
</div>


<!-- 2 COLUMN / IMAGE -->
<div class="container col-xxl-8 px-4 py-5">

  <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
    <div class="col-10 col-sm-8 col-lg-6">
      <img src="https://via.placeholder.com/400x300.png" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
    </div>
    <div class="col-lg-6">
      <h1 class="display-5 fw-bold lh-1 mb-3">Responsive left-aligned hero with image</h1>
      <p class="lead">Something something something, yada yada yada. Put whatever you want here, until then I am just going to put in placeholder text such as Lorem Ipsum. Ooo eee, ooo aahh ahh, bing bang walla walla bing bang. Ooo eee, ooo aahhh ahh bing bang!</p>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <%= link_to 'Recruit Me', interested_path, class: 'btn btn-primary btn-lg px-4 me-sm-3' %>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_header.html.erb
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
  <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
    <div class='logo'>
      <%= image_tag 'utng-logo.png', alt: 'UTNG', style: 'width: 100%;' %>
    </div>
    <div class='logo-text'>
      <b>Utah Army National Guard</b>
      <br>
      <small class='text-muted'>Recruiting</small>
    </div>
  </a>

  <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
    <li><a href="/" class="nav-link px-2">Home</a></li>
    <li><a href="/more-info" class="nav-link px-2">More Info</a></li>

    <% if current_user %>
      <li><a href="/leads" class="nav-link px-2">Leads</a></li>
    <% end %>
  </ul>

  <div class="col-md-3 text-end">
    <%= link_to 'I Want In', interested_path, class: 'btn btn-primary interested' %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Utah Army National Guard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render '/layouts/header' %>

      <div class="content">
        <% flash.each do |type, message| %>
          <div class="alert <%= flash_message_class(type) %>">
            <strong><%= type.capitalize %>!</strong> <%= message.html_safe %>
          </div>
        <% end %>
      </div>

      <div class="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/leads/_form.html.erb
<div class="container">
  <main class='mb-5'>
    <div class="py-5 text-center">
      <h2>I'm interested as fuuuuuuck</h2>
      <p class="lead">Maybe some more info on what they can expect after filling out the form.</p>
    </div>

    <div class="row g-5">
      <div class="col-lg-8 offset-lg-2">

        <%= form_for(@lead, html: { class: 'needs-validation' }) do |f| %>
          <div class="row g-3">
            <div class="col-sm-6">
              <%= f.label :first_name, title: 'First Name', class: 'form-label required' %>
              <%= f.text_field :first_name, class: 'form-control', required: true %>
              <div class="invalid-feedback">Valid first name is required.</div>
            </div>

            <div class="col-sm-6">
              <%= f.label :last_name, title: 'Last Name', class: 'form-label required' %>
              <%= f.text_field :last_name, class: 'form-control', required: true %>
              <div class="invalid-feedback">Valid last name is required.</div>
            </div>

            <div class="col-sm-6">
              <%= f.label :age, title: 'Age', class: 'form-label required' %>
              <%= f.select :age,
                    options_for_select(17...45, selected: 18),
                    {},
                    {title: 'Age', class: 'form-control form-select'} %>
            </div>

            <div class="col-sm-6">
              <%= f.label :gender, title: 'Gender', class: 'form-label required' %>
              <%= f.select :gender,
                    options_for_select(Lead.genders, selected: Lead.genders.select{|g| g == 'male'}),
                    {},
                    {title: 'Gender', class: 'form-control form-select'} %>
            </div>

            <div class="col-12">
              <%= f.label :email, title: 'Email', class: 'form-label required' %>
              <%= f.email_field :email, class: 'form-control', required: true %>
              <div class="invalid-feedback">Please enter a valid email address.</div>
            </div>

            <div class="col-12">
              <%= f.label :phone_number, title: 'Phone Number', class: 'form-label required' %>
              <%= f.text_field :phone_number, class: 'form-control', required: true %>
              <div class="invalid-feedback">Valid phone number is required.</div>
            </div>
          </div>

          <hr class="my-4">

          <div class="row g-3">
            <div class="col-12">
              <%= f.label :street, 'Address street', title: 'Address Street' %>
              <%= f.text_field :street, class: 'form-control' %>
            </div>

            <div class="col-sm-5">
              <%= f.label :city, title: 'City' %>
              <%= f.text_field :city, class: 'form-control' %>
            </div>

            <div class="col-sm-3">
              <%= f.label :state, title: 'State' %>
              <%= f.select :gender,
                    options_for_select(STATES, selected: STATES.select{|s| s == 'UT'}),
                    {},
                    {title: 'State', class: 'form-control form-select'} %>
            </div>

            <div class="col-sm-4">
              <%= f.label :zip, 'Zipcode', title: 'Zipcode' %>
              <%= f.text_field :zip, class: 'form-control' %>
            </div>

            <div class="col-12">
              <%= f.label :comment, 'Comments', title: 'Comments' %>
              <%= f.text_area :comment, rows: 10, class: 'form-control' %>
            </div>
          </div>

          <hr class="my-4">

          <% if current_user %>
            <div class="row g-3">
              <div class="col-12">
                <%= f.label :note, 'My Notes', title: 'Notes' %>
                <%= f.text_area :note, rows: 10, class: 'form-control' %>
              </div>
            </div>

            <hr class="my-4">
          <% end %>

          <%= f.submit 'Submit', class: 'w-100 btn btn-primary btn-lg' %>

        <% end %>
      </div>
    </div>
  </main>
</div>

app/views/leads/edit.html.erb
<h1>Editing <%= @lead.full_name %></h1>
<%= render 'form' %>

app/views/leads/index.html.erb
<h1>Listing all Leads</h1>

<div class="row">
  <div class="col-md-12">

    <table class="table table-dark table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone Number</th>
          <th>Age/Gen</th>
          <th>Street</th>
          <th>City</th>
          <th>State</th>
          <th>Zip</th>
          <th class='text-center'>Active?</th>
          <th class='text-center'>Recruited?</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @leads.each do |lead| %>
          <tr>
            <td><%= link_to(lead&.full_name, lead) %></td>
            <td><%= lead&.email&.downcase %></td>
            <td><%= display_phone(lead.phone_number) %></td>
            <td><%= "#{lead&.age}, #{lead&.gender.to_s}" %></td>
            <td><%= lead&.street %></td>
            <td><%= lead&.city %></td>
            <td><%= lead&.state %></td>
            <td><%= lead&.zip %></td>
            <td class='text-center'><%= lead.active_contact ? "&#10003;".html_safe : '' %></td>
            <td class='text-center'><%= lead.is_army ? "&#10003;".html_safe : '' %></td>
            <td>
              <div class="btn-group">
                <%= link_to 'edit', edit_lead_path(lead), class: 'btn btn-sm btn-primary' %>
                <%= link_to 'delete', lead_path(lead), method: 'delete', class: 'btn btn-sm btn-danger',
                            data: {confirm: "Do you want to delete #{lead&.full_name}?"} %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/leads/interested.html.erb
<%= render 'form' %>

app/views/leads/show.html.erb
<h1>Showing <%= @lead&.full_name %></h1>

<% @lead.attributes.reject{|a| %w[id updated_at].include?(a)}.each do |attr, val| %>
  <div class="row">
    <div class="col-md-2">
      <b><%= attr&.titleize %>:</b>
    </div>
    <div class="col-md-10">
      <% if val.is_a?(Time) %>
        <%= val.strftime('%d %b %Y') %>
      <% elsif attr == 'phone_number' %>
        <%= display_phone(val) %>
      <% else %>
        <%= val %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/leads/thank_you.html.erb
<h1>All Set!</h1>
<h3>SFC Pinon will be in touch shortly</h3>